### ISSUE TITLE
按返回键会退出

### ISSUE THREAD

**Issue by pexcn** [clowwindy/ShadowVPNAndroid#7]
开启shadowvpn之后，按返回键会退出。要按home键才行。。

**Comment by Joosun** [comment]
@pexcn 什么设备？

**Comment by pexcn** [comment]
@Joosun 刷了CyanogenMod 11的小米1...

**Comment by Joosun** [comment]
@pexcn 应该不会啊，返回的时候不会关掉 Service 的，你有改过代码么。或者你开启了自动杀应用。比如开发者模式里的后台限制。

**Comment by pexcn** [comment]
@Joosun 没改过代码，也没装安全卫士之类的，没开后台限制。
是Play商店下载的Beta版，开启之后按返回键，左上角的图标就没了。

**Comment by Joosun** [comment]
@pexcn 自己编译一下最新的吧。

**Comment by pexcn** [comment]
@Joosun 嗯，谢谢了。
